/**
    STORE FILM POSTERS AND PICTURES OF ACTORS AND DIRECTORS
CREATE TABLE IMAGES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    PIC BLOB(16K),
    PRIMARY KEY (ID)
);
*/

CREATE TABLE GENRES (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(128) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE ACTORS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE DIRECTORS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID)
);

/** COUNTRY */
CREATE TABLE REGIONS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(128),
    SHORT VARCHAR(32) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE FILMS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(128) NOT NULL,
    ORIGINAL_NAME VARCHAR(128),
    DESCRIPTION VARCHAR(128),
    IMAGE_NAME VARCHAR(128),
    FILM_YEAR INTEGER,
    FILM_TIME INTEGER,
    BOX INTEGER,
    DISK INTEGER,
    PRIMARY KEY (ID)
);

/** LINKING TABLES - MANY TO MANY */

CREATE TABLE FILM_GENRE (
    FILM_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    PRIMARY KEY (FILM_ID, GENRE_ID),
    FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID),
    FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID)
);

CREATE TABLE FILM_ACTOR (
    FILM_ID INTEGER NOT NULL CONSTRAINT FILM_FOREIGN_KEY REFERENCES FILMS(ID),
    ACTOR_ID INTEGER NOT NULL CONSTRAINT ACTOR_FOREIGN_KEY REFERENCES ACTORS(ID),
    PRIMARY KEY (FILM_ID, ACTOR_ID)
);

CREATE TABLE FILM_DIRECTOR (
    FILM_ID INTEGER NOT NULL,
    DIRECTOR_ID INTEGER NOT NULL,
    PRIMARY KEY (FILM_ID, DIRECTOR_ID),
    FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID),
    FOREIGN KEY (DIRECTOR_ID) REFERENCES DIRECTORS(ID)
);

CREATE TABLE FILM_REGION (
    FILM_ID INTEGER NOT NULL,
    REGION_ID INTEGER NOT NULL,
    PRIMARY KEY (FILM_ID, REGION_ID),
    FOREIGN KEY (FILM_ID) REFERENCES FILMS(ID),
    FOREIGN KEY (REGION_ID) REFERENCES REGIONS(ID)
);

CREATE VIEW PAGED_FILMS(ID, NUM) AS
SELECT ID, ROW_NUMBER() OVER ()
FROM FILMS

INSERT INTO REGIONS(NAME, SHORT) VALUES('Австралия','au');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Австрия','at');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Беларусь','by');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Болгария','bg');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Бразилия','br');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Великобритания','uk');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Венгрия','hu');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Венесуэлла','ve');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Вьетнам','vn');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Германия','de');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Гонконг','hk');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Греция','gr');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Дания','dk');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Израиль','il');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Индия','in');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Ирландия','ie');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Исландия','is');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Испания','es');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Италия','it');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Канада','ca');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Китай','cn');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Куба','cu');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Латвия','lv');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Литва','lt');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Мексика','mx');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Новая Зеландия','nz');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Нидерланды','nl');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Норвегия','no');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Пакистан','pk');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Польша','pl');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Португалия','pt');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Россия','ru');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Румыния','ro');
INSERT INTO REGIONS(NAME, SHORT) VALUES('СССР','su');
INSERT INTO REGIONS(NAME, SHORT) VALUES('США','us');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Сербия','rs');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Словакия','sk');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Турция','tr');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Финляндия','fi');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Франция','fr');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Чехословакия','cs');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Чехия','cz');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Швеция','se');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Швейцария','ch');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Эстония','ee');
INSERT INTO REGIONS(NAME, SHORT) VALUES('ЮАР','za');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Южная Корея','kr');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Югославия','yu');
INSERT INTO REGIONS(NAME, SHORT) VALUES('Япония','jp');

/*
DROP TABLE "APP"."FILM_ACTOR";
DROP TABLE "APP"."FILM_DIRECTOR";
DROP TABLE "APP"."FILM_GENRE";
DROP TABLE "APP"."FILM_REGION";
DROP TABLE "APP"."ACTORS";
DROP TABLE "APP"."DIRECTORS";
DROP TABLE "APP"."FILMS";
DROP TABLE "APP"."GENRES";
DROP TABLE "APP"."IMAGES";
DROP TABLE "APP"."REGIONS";
DROP VIEW "APP"."PAGED_FILMS";
*/
